### ISSUE TITLE
Token Leaked

### ISSUE THREAD

**Issue by EJH2** [ShibaXD/Gamer-Discord-Bot#1]
https://github.com/ShibaXD/Gamer-Discord-Bot/blob/d84479b3925584dd9b183ff87f46be12f572e2cf/secrets.py#L3
https://github.com/ShibaXD/Gamer-Discord-Bot/blob/d84479b3925584dd9b183ff87f46be12f572e2cf/bot.py#L14

**Comment by ghost** [comment]
Wtf
